# Generated by Django 6.1.1 on 2026-10-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0002_fotografia_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="fotografia",
            name="publicado",
            field=models.BooleanField(default=False),
        ),
    ]
